### ISSUE TITLE
same as #172

### ISSUE THREAD

**Issue by clauu-mara** [pitpalac36/Testing-Internship#173] opened 2021-08-05 10:39 UTC
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/ProductTests.cs#L114

**Comment by meOtniel** [comment] 2021-08-05 10:47
not a bug, wont fix

**Closed as completed by meOtniel** 2021-08-05 10:47 UTC
