### ISSUE TITLE
you can use a single space before and after each operator and brackets

### ISSUE THREAD

**Issue by clauu-mara** [pitpalac36/Testing-Internship#170] opened 2021-08-05 10:30 UTC
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/ProductTests.cs#L92

**Comment by meOtniel** [comment] 2021-08-05 10:55
not a bug, won't fix

**Closed as completed by meOtniel** 2021-08-05 10:55 UTC
